Received: from [85.7.26.215] by mail.clarkzoo.org (ArGoSoft Mail Server .NET v.1.0.8.6) with ESMTP (EHLO 215-26.7-85.cust.bluewin.ch)
	for <violet@violetdeville.com>; Mon, 19 Jan 2015 12:49:37 -0800
From: "John" <violetugn@bluewin.ch>
To: violet@violetdeville.com
Subject: ****SPAM**** (27.6 / 5.0)  Hi, my dear friend!Date: Mon, 19 Jan 2015 21:50:26 +0200
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="MIMEBoundarye18b19149da7f918a655104b59756e4e"
List-Unsubscribe: <mailto:leave-ef928ef359167c0dd2912b8e95383f11@bluewin.ch>
Reply-To: violetugn@bluewin.ch
Message-ID: <97C52-19550330-97070415-2015.01.19-21.50.26-violet#violetdeville.com@215-26.7-85.cust.bluewin.ch>
SPF-Received: none
X-FromIP: 85.7.26.215
X-HostName:215-26.7-85.cust.bluewin.ch

Hello, great to find your email.
I am from Russia, looking for an acquaintance with you.
I am young, beautiful girl who is eager to find love.

Please visit my short intro with photos...

