68.232.135.212	GhostSenderBuster::Rejected IP address (68.232.135.212), From header doesn't contain a  valid valid e-mail address (Debra Knutson <Debra.Knutson@Hilton.com>)
Received: from [68.232.135.212] by mail.clarkzoo.org (ArGoSoft Mail Server .NET v.1.0.8.6) with ESMTP (EHLO esa8.hilton.iphmx.com)
	for <amber@clarkzoo.org>; Tue, 17 Feb 2015 17:30:31 -0800
X-IronPort-AV: E=Sophos;i="5.09,595,1418104800"; 
   d="jpg'145?png'145,150?scan'145,150,208,217,150,145";a="97872703"
Received: from ftc-tls.hilton.com (HELO mail.hilton.com) ([167.187.100.2])
  by esa8.hilton.iphmx.com with ESMTP/TLS/AES128-SHA; 17 Feb 2015 17:22:01 -0600
Received: from HFWMXMSG13PH.hotels.ad.hilton.com (10.80.40.45) by
 HFWMRMSG04PH.hotels.ad.hilton.com (10.80.200.54) with Microsoft SMTP Server
 (TLS) id 14.3.224.2; Tue, 17 Feb 2015 18:21:25 -0500
Received: from HFWMXMSG05PH.hotels.ad.hilton.com ([169.254.3.58]) by
 HFWMXMSG13PH.hotels.ad.hilton.com ([169.254.7.197]) with mapi id
 14.03.0224.002; Tue, 17 Feb 2015 18:21:27 -0500
From: Debra Knutson 
To: "amber@clarkzoo.org" <amber@clarkzoo.org>
CC: "smarier@gmail.com" <smarier@gmail.com>
Subject: reservation for Norwescon 2015
Thread-Topic: reservation for Norwescon 2015
Thread-Index: AdBLCBsCYKeYhyByREOPojqVlT+mDQ==
Date: Tue, 17 Feb 2015 23:21:26 +0000
Message-ID: <9ACE65E1F523304CA69442543B2990280AB77FCD@HFWMXMSG05PH.hotels.ad.hilton.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach: yes
X-MS-TNEF-Correlator:
x-originating-ip: [10.80.202.27]
Content-Type: multipart/related;
	boundary="_005_9ACE65E1F523304CA69442543B2990280AB77FCDHFWMXMSG05PHhot_";
	type="multipart/alternative"
MIME-Version: 1.0
Return-Path: <Debra.Knutson@Hilton.com>
SPF-Received: pass
X-FromIP: 68.232.135.212
X-HostName: esa8.hilton.iphmx.com

Test data.