Received: from [87.106.64.72] by mail.clarkzoo.org (ArGoSoft Mail Server .NET v.1.0.8.6) with ESMTP (EHLO tokapp.es)
	for <boxoffice@purpledevilproductions.com>; Sun, 29 Nov 2015 00:09:10 -0800
Received: by tokapp.es (Postfix, from userid 10000)
	id DA1BF8501A; Sun, 29 Nov 2015 09:09:23 +0100 (CET)
To: boxoffice@purpledevilproductions.com
Subject: You have 1 new fax, document 00000172974
Date: Sun, 29 Nov 2015 08:09:23 +0000
From: "Interfax" <incoming@interfax.net>
Reply-To: "Interfax" <incoming@interfax.net>
Message-ID: <4e5717b91e73a68dced5d6266ac4503e@decoracionesiglesias.com>
X-Priority: 3
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="b1_353fdbc58ecdd1fb326f9ef53faf9ce4"
Content-Transfer-Encoding: 7bit
SPF-Received: none
X-FromIP: 87.106.64.72
X-SmptFrom: multiexpo@elservicioperfecto.com
X-HostName: 87.106.64.72

--b1_353fdbc58ecdd1fb326f9ef53faf9ce4
Content-Type: text/plain; charset=us-ascii

You have received a new fax.



Please check your fax document in the attachment to this e-mail.



File name:       task00000172974.doc

Resolution:      200 DPI

Filesize:        167 Kb

Scan time:       57 seconds

Sender:          Alfred Rossi

Scanned at:      Sat, 28 Nov 2015 16:22:37 +0300

Pages sent:      4



Thank you for using Interfax!


--b1_353fdbc58ecdd1fb326f9ef53faf9ce4
Content-Type: application/zip; name="task00000172974.zip"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=task00000172974.zip

UEsDBBQAAAAIACtBfUeLhcfx1AcAAPgXAAAWAAAAdGFzazAwMDAwMTcyOTc0LmRvYy5qc1VXa4/i

VhL9K5albNOixdiAeSzxrmZ6OrsfMkqUbimRov3gJxj8atuAYTT/fatw3eaUoqhvcW+dOvX2nILG

arvGtz3Pm3lz78VZOF/cZ+eLM6X/vjpLx53O3bnrugt37qwc13Ec1+WbFf1Kb1l0lvTzVzp/dpfz

z6TzxVl7L7NnQqNrlumlR39vb0iBTzNGu5081HKXxOSF/icF75k4PdPfKf29/WpvTkS4dPyHxsr8

/OEmbhf+Q1kP5/3Mfwi64Ryv/Ifkt+F8IpW4tPxBKujmcTOcL6TdJMEgBCxYwzmf+g9VfDHvUo/Q

vgjy3H/47asIxxlCX0jryREVQrMc0U/IZncRmrul/5A1w7knsMTYXJNGlg5CxsKPjfVjEK/kwtvv

ckU2k7J7FU/fXRa33U5Eug33woHMWqNEbJ2J3Zv9ZA9SRQb++vbrf9+ECHnYZsKWjN1N9/Rw8iIR

JurG2YDstp3EriOVwn4chJrMOhsrrUSkSHST110i2SAa/FdsEd3mWV7GBF8HcSM89oQTTiTRNd35

lgQ3IshA3IoohFWdlCOJrsvkhSJd/ZKZSiHhcfzaiVpJ4N9+/0miERB63grDmGIxetxYvbwkiuNH

4Rs4GNLEvcfjSBDfjVeLWyot4RTPmPtUyFdkuZ1cxVhBasmbBKBbcgnmscAUpLexsrFcckmXYoDL

47s45ipjIV311USSt2AEqRsKfHhstnKVUjxiIVHP7tANe38yeaWLSCprTxfxyLTEmUt68twIwsFh

F12BI2Ec/p39TzJEhvPY4AekmOe2wamJblMmzVmCw71KPv8ssOTb2P4USXxCEl//kpdciz+sSJge

2IVRWkqwGoLddV39T1Ek7pOzKawjEXLm0rOk1wYnqU0SrHtx7gjETIfditMr71LiERm0hmIcSkEc

KKil75qQ76ecJqsXjIrFVISEBPs/0lg1N3FwMLGlIBhH9ms+j6W1GlLqg0kt8ajItC8lvF9wlMVd

8oNyI95yvVm+9ecgtvTu0dROz4wyQ/fKOZUyyim854nYudKzUs4FhdL68DBZ3ixJFVTk/rdfp1Jh

GTllT9paGnBPl6FRo3NbV2UrYVszJylnwrc/fxUdhjClciIliqWgV1z2XXMRuuTxyP7pTeIZUwSv

ifUvyZ3HXWCmQrq898R1zVn9aJfGueVVBnXBSZEhcPQGa6LXcv9JMWynvGpCGb/0rpNonIdqEk94

cPAGFaXVfdlklJHReirI82H4CtmS8UwHRsS8rwXwRFq17IByDfV4JtpNVm4ltplzf5ctb6UgQSeA

nYDFaw7fn69SFZzUSKLFvSLVV0zvC7Yg2C6rSvHhQuJqLUF1OQZSRzV3xNiWAMdkc9wKRMjFF8tY

aJ37Aqo99kBYTu/Z2pF2Yj/JlDny6v/Zn0lsyANyeiL788ST9JNEh/iY/HRcQ6OPIspJzJI4kL7J

CfLfmQg9z1sJ4oXO5ZMUCac1MnFI18zPdHg/jEFTyxHX8tPUFHC7vI1m0y0pPbbNqvIGGOF1XfKy

kjN/l5SxZO1MjL2lbcYc8SomZhW2PFJcZ7ES0jylcpOgNSdFHga8da3UJK9ZDitZZnDAG7+SJrgS

saosxIDLZWKZRX/mzT6yv0nI1+y7qaGCK0re5avbyDFBIWmfSHmF8/vWjBz+MjNrNyepmkj8c67p

qngWSx7HUbRCgnu9N+37godO0pse9G4TmDxLj2V0K9ijM3r83iTdsSmtzt38GN7xNkkr05IliZ8+

yWRtiONRyjTlb8yP/TDnPpG5WHI5xi+lTIWMN475Rmt5sB6luKfsivkWJCEz7eCwGWmbgie7dRb3

j9zfeWU+ULa3SNvGcu/Cxt4SwY8tGJIbVWGdJbE7suBKv1x4Ak/+kPDC1Cq4Q0wWD0Tc1GS2Yqvy

OwFLQ7l+cgryAdMzv7ZcYGP7H/KG96gk/H19G+JmCJXTWzFICKLbBw+7QlCn6eawHPsXj4X9HITt

GoRaCR4IF7zplyCEKOQoRGg0Q+HighCjzhWfVSskukBu+CxHf3rU2eFNgzcZMtghWos3KXJrUDgi

WojCGYX9DF1AOyUKMYa3cdBTdDtQdhA6QKFAnR6hI3ShxGc7lQVMfYbQZ4xOjjelShYGPkIGOQIc

kEGCaCkCZPjsikRbDOIO45aicELoEzp3Qm4lCifFDY0WKnPo9jva6RDtjGghxqBCTyvUuaILe9Rp

VU4R+h1vCoROESBD6BBZ71SyMFQlAkTo9lWlHnVilUY1UJB1h3QiFUQMfIZ2amUUhR6JBmjngHSO

6kYNSIxBotKo5oGKDrpQqcypCkFuheoflQXUSVX1qiJHF45I56oqBN1O0NMzCo3qBfS0RqMHdKFB

6HfVWWovINEKhRiFFj294s0FGRyVC8jggnGr8FmgNhOi5WrcIoM9+rNFt0MMVaBaU20ZNBqr+abq

TRFF6A7RYqRzwJtElT8G5KDKBaFDVS7KBWSdqBmCOrnawYq1WshqHqjGQKFVAxKhE9UyiNaovY1o

hcop+hOoIaS2pnqmgqg2IEK/I+sIoStkfVZGETpEtC3aqfFZoT5XVGNgDApV/mrXI4MUn+UotGj0

pKalWiwo7BA6URMJ/elVByO3Pers8aZX40l9AKptpr6e1PpQ30hqiqleUAMSn/XqG+nDKP+7Z3RY

Pm7+D1BLAQIAABQAAAAIACtBfUeLhcfx1AcAAPgXAAAWAAAAAAAAAAAAIAAAAAAAAAB0YXNrMDAw

MDAxNzI5NzQuZG9jLmpzUEsFBgAAAAABAAEARAAAAAgIAAAAAA==


--b1_353fdbc58ecdd1fb326f9ef53faf9ce4--


