Received: from [177.239.68.144] by mail.clarkzoo.org (ArGoSoft Mail Server .NET v.1.0.8.6) with ESMTP (EHLO SanMartin3.cpe.oax.cablemas.com.mx)
	for <donny@clarkzoo.org>; Thu, 10 Dec 2015 15:08:00 -0800
Message-ID: <1669097433.SIM_324D0AFD3327@clarkzoo.org>
From: =?UTF-8?B?S29yZXkgTWVyY2Fkbw==?= <MercadoKorey595@cablemas.com.mx>
To: =?UTF-8?B?ZG9ubnk=?= <donny@clarkzoo.org>
Subject: =?UTF-8?B?UGF5bWVudCBOcjogMDIyNjY5OTIvOEE5QzA1NTg=?=
Date: Thu, 10 Dec 2015 17:08:28 -0500
Reply-To: =?UTF-8?B?ZG9ubnk=?= <donny@clarkzoo.org>
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="----=_NexPart_002"
SPF-Received: softfail
X-FromIP: 177.239.68.144
X-SmptFrom: MercadoKorey595@cablemas.com.mx
X-HostName: 

------=_NexPart_002
Content-Type: multipart/alternative;
	boundary="----=_NexPart_000"

------=_NexPart_000
Content-Type: text/plain;
	charset=utf-8
Content-Transfer-Encoding: base64

RGVhciBDbGllbnQsDQoNCk91ciBmaW5hbmNlIGRlcGFydG1lbnQgaGFzIHByb2Nlc3NlZCB5b3Vy
IHBheW1lbnQsIHVuZm9ydHVuYXRlbHkgaXQgaGFzIGJlZW5kZWNsaW5lZC4NClBsZWFzZSwgZG91
YmxlIGNoZWNrIHRoZSBpbmZvcm1hdGlvbiBwcm92aWRlZCBpbiB0aGUgaW52b2ljZSBkb3duYmVs
b3cgYW5kIGNvbmZpcm0geW91ciBkZXRhaWxzLg0KDQpUaGFuayB5b3UgZm9yIHVuZGVyc3RhbmRp
bmcu

------=_NexPart_000
Content-Type: text/html;
	charset=utf-8
Content-Transfer-Encoding: base64

PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBYSFRNTCAxLjAgVHJhbnNpdGlvbmFs
Ly9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSL3hodG1sMS9EVEQveGh0bWwxLXRyYW5zaXRpb25h
bC5kdGQiPg0KPGh0bWwgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwiPg0KDQo8
aGVhZD4NCjxtZXRhIGNvbnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD11dGYtOCIgaHR0cC1lcXVp
dj0iQ29udGVudC1UeXBlIiAvPg0KPHRpdGxlPkRlYXIgQ2xpZW50PC90aXRsZT4NCjwvaGVhZD4N
Cg0KPGJvZHk+DQoNCjxwPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IG1lZGl1bTsgZm9udC1mYW1p
bHk6ICdDb3VyaWVyIE5ldyciPkRlYXIgQ2xpZW50LDxiciAvPg0KPGJyIC8+DQpPdXIgZmluYW5j
ZSBkZXBhcnRtZW50IGhhcyBwcm9jZXNzZWQgeW91ciBwYXltZW50LCB1bmZvcnR1bmF0ZWx5IGl0
IGhhcyBiZWVuDQpkZWNsaW5lZC48YnIgLz4NClBsZWFzZSwgZG91YmxlIGNoZWNrIHRoZSBpbmZv
cm1hdGlvbiBwcm92aWRlZCBpbiB0aGUgaW52b2ljZSBkb3duDQpiZWxvdyBhbmQgY29uZmlybSB5
b3VyIGRldGFpbHMuPGJyIC8+DQo8YnIgLz4NClRoYW5rIHlvdSBmb3IgdW5kZXJzdGFuZGluZy48
L3NwYW4+PC9wPg0KDQo8L2JvZHk+DQoNCjwvaHRtbD4=

------=_NexPart_000--

------=_NexPart_002
Content-Type: application/zip;
	name="SCAN_invoice_02266992.zip"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="SCAN_invoice_02266992.zip"

UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA==

------=_NexPart_002--

